### ISSUE TITLE
Update the README with installation instruction to use it in Windows 

### ISSUE THREAD

**Issue by iamsiddhantsahu** [karaimer/camera-pipeline-dng-sdk#1]
@karaimer Pl update the `README.md` with instructions on how to use this application with https://github.com/karaimer/camera-pipeline-UI 

https://docs.google.com/document/d/1WzeZ-9U4aTuwFpcX-8GgAy0wT9ERF41ltjr-jJ-NMCo/ 
Didn't find installation instruction in this document.

**Comment by karaimer** [comment]
**camera-pipeline-UI** calls the executable that is produced by the **camera-pipeline-dng-sdk**. Once the SDK is built, the executable is placed in the following path: camera-pipeline-dng-sdk/Adobe_finalSDK/dng_sdk/targets/win/debug/. 

I'll update the readme.

**Comment by karaimer** [comment]
The same executable is also used in a nonUI version of the pipeline which is added in another repository named [camera-pipeline-nonUI](https://github.com/karaimer/camera-pipeline-nonUI). 

I am closing the issue now.

**Comment by iamsiddhantsahu** [comment]
@karaimer I downloaded the [camera-pipeline-UI](https://github.com/karaimer/camera-pipeline-UI) and [camera-pipeline-dng-sdk](https://github.com/karaimer/camera-pipeline-dng-sdk), by default I see a executable `dng_validate.exe` executable in [https://github.com/karaimer/camera-pipeline-dng-sdk/tree/master/Adobe_finalSDK/dng_sdk/targets/win/debug](https://github.com/karaimer/camera-pipeline-dng-sdk/tree/master/Adobe_finalSDK/dng_sdk/targets/win/debug), then do we need to rebuilt the [camera-pipeline-dng-sdk](https://github.com/karaimer/camera-pipeline-dng-sdk)? We don't have to add the path of executable in the environment variable? Pl provide in details the step by step process to use this interesting application. Excuse me for asking such trivial questions.

**Comment by karaimer** [comment]
Correct, no need to rebuilt the [camera-pipeline-dng-sdk](https://github.com/karaimer/camera-pipeline-dng-sdk). We don't have to add the path of the executable in the environment variable. Once the [camera-pipeline-UI](https://github.com/karaimer/camera-pipeline-UI) or [camera-pipeline-nonUI](https://github.com/karaimer/camera-pipeline-nonUI) is downloaded, you can start using it with Windows. For Mac OS, you need to use the executable for Mac OS. 

[camera-pipeline-nonUI](https://github.com/karaimer/camera-pipeline-nonUI) serves as an example to produce a demosaiced (stage 4) and sRGB (i.e., final) image without a user interface. Also, I prepared a few examples [here ](https://docs.google.com/document/d/1WzeZ-9U4aTuwFpcX-8GgAy0wT9ERF41ltjr-jJ-NMCo/edit) to show how the [camera-pipeline-UI](https://github.com/karaimer/camera-pipeline-UI) is used. 

Please let me know if this helps.

**Comment by iamsiddhantsahu** [comment]
Yes @karaimer, I downloaded and put the [camera-pipeline-UI](https://github.com/karaimer/camera-pipeline-UI) and [camera-pipeline-dng-sdk](https://github.com/karaimer/camera-pipeline-dng-sdk) in the same folder. Now if I got into the [https://github.com/karaimer/camera-pipeline-dng-sdk/tree/master/Adobe_finalSDK/dng_sdk/targets/win/debug](https://github.com/karaimer/camera-pipeline-dng-sdk/tree/master/Adobe_finalSDK/dng_sdk/targets/win/debug) and run the `dng_validate.exe`, the command prompt opens and disappears immediately and I don't see the UI as mentioned in [doc ](https://docs.google.com/document/d/1WzeZ-9U4aTuwFpcX-8GgAy0wT9ERF41ltjr-jJ-NMCo/edit#). Am I doing something wrong? Not that I don't have Matlab installed in my PC.

**Comment by karaimer** [comment]
UI is made using Matlab. You need to run Matlab script named `camera_pipeline.m` which calls `dng_validate.exe`.

**Comment by iamsiddhantsahu** [comment]
I ran `camera_pipeline.m` script in Matlab R2015b. Got this error 

> Error using imread (line 349)
> File ".\Adobe_DNG_SDK_Pipeline_v4.bmp" does not exist.
> 
> Error in camera_pipeline>camera_pipeline_OpeningFcn (line 80)
> pipeline_image = im2double(imread(fullfile('.','Adobe_DNG_SDK_Pipeline_v4.bmp')));
> 
> Error in gui_mainfcn (line 220)
>     feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});
> 
> Error in camera_pipeline (line 42)
>     gui_mainfcn(gui_State, varargin{:});`

I am using Windows 10. Why am I getting error in imread? I checked the directory containing `camera_pipeline.m` also has `Adobe_DNG_SDK_Pipeline_v4.bmp`. Is the path wrong?

**Comment by karaimer** [comment]
I've just got a fresh copy of [camera-pipeline-UI](https://github.com/karaimer/camera-pipeline-UI). I am running Windows 10 as well. The code works properly. Also, I tested on a different computer and It works without errors. 
Please make sure that the `Adobe_DNG_SDK_Pipeline_v4.bmp` is in the directory. Also, please make sure that antivirus software does not block the `dng_validate.exe`.

**Comment by iamsiddhantsahu** [comment]
Yes it ran. But unable to open a `.dng` file. Getting this error 

> camera_pipeline
> at slider value 10
> Validating "camera"... 
> Validating "pipeline\camera-pipeline-UI-master\NIKOND40_0008_dng_converted_stage10.tif"... 
> Validating "F:\Papers\awb\software"... 
> Validating "camera"... 
> Validating "pipeline\camera-pipeline-UI-master\NIKOND40_0008_dng_converted.dng"... 
> *** Error: Unable to open file (camera) *** 
> *** Error: Unable to open file (pipeline\camera-pipeline-UI-master\NIKOND40_0008_dng_converted_stage10.tif) *** 
> *** Error: Unable to open file (F:\Papers\awb\software) *** 
> *** Error: Unable to open file (camera) *** 
> *** Error: Unable to open file (pipeline\camera-pipeline-UI-master\NIKOND40_0008_dng_converted.dng) *** 
> Error using imread (line 349)
> File "F:\Papers\awb\software camera pipeline\camera-pipeline-UI-master\NIKOND40_0008_dng_converted_stage10.tif" does not exist.
> 
> Error in camera_pipeline>pushbutton1_Callback (line 377)
>         handles.myData.image = imread(stage10OutputFileName);%comment here when dng save tests.
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in camera_pipeline (line 42)
>     gui_mainfcn(gui_State, varargin{:});
> 
> Error in
> matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)camera_pipeline('pushbutton1_Callback',hObject,eventdata,guidata(hObject))
>  
> Error while evaluating UIControl Callback

I tried putting the `.dng` file in `Documents\MATLAB` but still getting the same error. And also in the currently directory where `camera_pipeline.m` script is present. Still didn't work for me. I am running the MATLAB application as administrator, so issues with file accessibility permissions.

**Comment by karaimer** [comment]
Please remove whitespace characters in your path. That looks like a problem based on the error message. 
For example, `software camera pipeline` to `software_camera_pipeline`.

**Comment by iamsiddhantsahu** [comment]
@karaimer Thanks a lot. It worked for me. Excuse me for asking such trivial questions. Would experiment with different phases of the camera pipeline. Interested to learn the pipeline stages of a camera. It's a great software, helps people learn. 
Is there any source/blog/article/paper that explains these phases in details? I am reading your paper on "Improving Color Reproduction Accuracy of Cameras".

**Comment by karaimer** [comment]
You're welcome, glad that it worked. 

It's based on [this ](https://karaimer.github.io/camera-pipeline/paper/Karaimer_Brown_ECCV16.pdf) paper. There is a [readme](https://docs.google.com/document/d/1WzeZ-9U4aTuwFpcX-8GgAy0wT9ERF41ltjr-jJ-NMCo/edit) for the [UI](https://github.com/karaimer/camera-pipeline-UI). 

Also, the [non-UI](https://github.com/karaimer/camera-pipeline-nonUI) code example is useful when you need to render lots of images. It's an example to produce a demosaiced (stage 4) and sRGB (i.e., final) image without a user interface.
