### ISSUE TITLE
how to build it

### ISSUE THREAD

**Issue by XiaoyuShi97** [karaimer/camera-pipeline-dng-sdk#2]
Hi, this is definitely the best software isp pipeline. I hope to read and understand implement details. Could you please give some instructions on how to build and run this project?

**Comment by karaimer** [comment]
Thanks, I'm glad to hear that. 

The original DNG SDK comes with a few dependencies, such as JPEG, EXIF libraries, etc. This repository contains all of the dependencies and makes it possible to compile them all together. 

I was able to compile the repository with Visual C++ 2010 Express in Windows 10. However, I didn't test it recently. So, I recommend you try to compile a repository clone with Visual C++ 2010 Express in Windows 10.
